version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8090:8090"
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8090"
    tty: true